In [6]:
import pandas as pd
import numpy as np

In [7]:
Data=pd.read_csv("LR_1D_data.csv")
Data

y     x
0    6.070736 -1.00
1    9.120318 -0.95
2    4.725397 -0.90
3    9.267612 -0.85
4    8.020143 -0.80
..        ...   ...
95 -10.355203  3.75
96  -4.428707  3.80
97  -6.005354  3.85
98  -7.609459  3.90
99  -9.304869  3.95

[100 rows x 2 columns]

In [8]:
#W is the slope array
W=np.linspace(-6,6,13)
W

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [9]:
#b is the intercept array
b=np.linspace(0,10,11)
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
m=W.shape[0]
n=b.shape[0]
J=np.zeros((m,n))
for i in range(len(W)):
    for j in range(len(b)):
        J[i,j]=np.sum(np.square(Data['y']-W[i]*Data['x']-b[j]))/Data['x'].shape[0]
        

13

In [11]:
#J is the cost function (mse)
J

array([[112.27215893,  94.4161926 ,  78.56022628,  64.70425995,
         52.84829363,  42.9923273 ,  35.13636097,  29.28039465,
         25.42442832,  23.568462  ,  23.71249567],
       [ 76.35155789,  61.44559156,  48.53962523,  37.63365891,
         28.72769258,  21.82172626,  16.91575993,  14.00979361,
         13.10382728,  14.19786096,  17.29189463],
       [ 48.94845684,  36.99249052,  27.03652419,  19.08055787,
         13.12459154,   9.16862522,   7.21265889,   7.25669256,
          9.30072624,  13.34475991,  19.38879359],
       [ 30.0628558 ,  21.05688948,  14.05092315,   9.04495682,
          6.0389905 ,   5.03302417,   6.02705785,   9.02109152,
         14.0151252 ,  21.00915887,  30.00319254],
       [ 19.69475476,  13.63878843,   9.58282211,   7.52685578,
          7.47088946,   9.41492313,  13.35895681,  19.30299048,
         27.24702415,  37.19105783,  49.1350915 ],
       [ 17.84415372,  14.73818739,  13.63222107,  14.52625474,
         17.42028841,  22.31432209,  29.2

In [12]:
import plotly.graph_objects as go
fig=go.Figure(data=go.Surface(z=J,x=b,y=W))
fig.update_traces(contours_z=dict(show=True,usecolormap=True,project_z=True))
fig.update_layout(title='Linear model',scene=dict(xaxis_title='b',yaxis_title='W',zaxis_title='mse'))
fig.show()